name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: otter
          # the following are defaults on github actions
          description: ""
          pandoc: "README.md"
          toc: true
          version: "NVIM v0.8.1"
          demojify: false
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto generate docs'
          branch: ${{ github.head_ref }}

